/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ProfileManagementApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierProfileManagementCustom } from "./client-custom";

export class VisierProfileManagement extends VisierProfileManagementCustom {
  readonly profileManagement: ProfileManagementApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.profileManagement = new ProfileManagementApi(configuration);
  }

}
