/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FailedAccessibleTenantProfileAssignmentDTO } from './failed-accessible-tenant-profile-assignment-dto';
import { SuccessfulAccessibleTenantProfileAssignmentDTO } from './successful-accessible-tenant-profile-assignment-dto';
import { TenantCodeErrorDTO } from './tenant-code-error-dto';
import { UserIdErrorDTO } from './user-id-error-dto';

/**
 * 
 * @export
 * @interface AccessibleTenantProfileAssignmentResponseDTO
 */
export interface AccessibleTenantProfileAssignmentResponseDTO {
    /**
     * If true, an error is generated by the request.
     * @type {boolean}
     * @memberof AccessibleTenantProfileAssignmentResponseDTO
     */
    'errors'?: boolean;
    /**
     * A list of objects representing any tenants that returned errors.
     * @type {Array<TenantCodeErrorDTO>}
     * @memberof AccessibleTenantProfileAssignmentResponseDTO
     */
    'badTenantCodes'?: Array<TenantCodeErrorDTO>;
    /**
     * A list of objects representing the user IDs that may not be valid.
     * @type {Array<UserIdErrorDTO>}
     * @memberof AccessibleTenantProfileAssignmentResponseDTO
     */
    'badUserIds'?: Array<UserIdErrorDTO>;
    /**
     * A list of objects representing any errors during the assignment operation.
     * @type {Array<FailedAccessibleTenantProfileAssignmentDTO>}
     * @memberof AccessibleTenantProfileAssignmentResponseDTO
     */
    'failedAssignments'?: Array<FailedAccessibleTenantProfileAssignmentDTO>;
    /**
     * A list of user IDs that were successfully assigned the profiles.
     * @type {Array<SuccessfulAccessibleTenantProfileAssignmentDTO>}
     * @memberof AccessibleTenantProfileAssignmentResponseDTO
     */
    'successfulAssignments'?: Array<SuccessfulAccessibleTenantProfileAssignmentDTO>;
}

