/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TargetTenantCodeDTO } from './target-tenant-code-dto';

/**
 * 
 * @export
 * @interface AccessibleTenantProfileAssignmentRequestDTO
 */
export interface AccessibleTenantProfileAssignmentRequestDTO {
    /**
     * A list of users to assign this profile.
     * @type {Array<string>}
     * @memberof AccessibleTenantProfileAssignmentRequestDTO
     */
    'targetUserIds'?: Array<string>;
    /**
     * A list of objects representing the  analytic tenants for profiles assigned to the users.
     * @type {Array<TargetTenantCodeDTO>}
     * @memberof AccessibleTenantProfileAssignmentRequestDTO
     */
    'targetTenantCodes'?: Array<TargetTenantCodeDTO>;
    /**
     * An inclusive date-time when this profile is active.
     * @type {string}
     * @memberof AccessibleTenantProfileAssignmentRequestDTO
     */
    'validityStartTime'?: string;
    /**
     * An exclusive date-time when this profile is no longer active.
     * @type {string}
     * @memberof AccessibleTenantProfileAssignmentRequestDTO
     */
    'validityEndTime'?: string;
}

