/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProfileAssignedForAccessibleTenantDTO } from './profile-assigned-for-accessible-tenant-dto';

/**
 * 
 * @export
 * @interface AllProfileAssignedForAccessibleTenantDTO
 */
export interface AllProfileAssignedForAccessibleTenantDTO {
    /**
     * A list of objects representing the user profiles assigned to the user and their validity range.
     * @type {Array<ProfileAssignedForAccessibleTenantDTO>}
     * @memberof AllProfileAssignedForAccessibleTenantDTO
     */
    'assignedProfilesForAccessibleTenant'?: Array<ProfileAssignedForAccessibleTenantDTO>;
}

