/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ErrorDTO
 */
export interface ErrorDTO {
    /**
     * The root cause identifier that allows Visier to determine the source of the problem.
     * @type {string}
     * @memberof ErrorDTO
     */
    'rootCauseId'?: string;
    /**
     * A brief identifier of the type of error.
     * @type {string}
     * @memberof ErrorDTO
     */
    'errorCode'?: string;
    /**
     * A description of the error that occurred.
     * @type {string}
     * @memberof ErrorDTO
     */
    'errorMessage'?: string;
}

