/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FailedLocalTenantProfileRevokeDTO
 */
export interface FailedLocalTenantProfileRevokeDTO {
    /**
     * The impacted user ID.
     * @type {string}
     * @memberof FailedLocalTenantProfileRevokeDTO
     */
    'userId'?: string;
    /**
     * The details about the error.
     * @type {string}
     * @memberof FailedLocalTenantProfileRevokeDTO
     */
    'message'?: string;
}

