/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FailedLocalTenantProfileRevokeDTO } from './failed-local-tenant-profile-revoke-dto';
import { SuccessfulLocalTenantProfileAssignmentDTO } from './successful-local-tenant-profile-assignment-dto';

/**
 * 
 * @export
 * @interface LocalTenantProfileRevokeResponseDTO
 */
export interface LocalTenantProfileRevokeResponseDTO {
    /**
     * A list of objects representing any errors that occurred during the assignment operation.
     * @type {Array<FailedLocalTenantProfileRevokeDTO>}
     * @memberof LocalTenantProfileRevokeResponseDTO
     */
    'failed'?: Array<FailedLocalTenantProfileRevokeDTO>;
    /**
     * A list of the user IDs that successfully had a profile removed.
     * @type {Array<SuccessfulLocalTenantProfileAssignmentDTO>}
     * @memberof LocalTenantProfileRevokeResponseDTO
     */
    'succeeded'?: Array<SuccessfulLocalTenantProfileAssignmentDTO>;
}

