/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface LocalTenantProfileAssignmentRequestDTO
 */
export interface LocalTenantProfileAssignmentRequestDTO {
    /**
     * A list of users to assign this profile.
     * @type {Array<string>}
     * @memberof LocalTenantProfileAssignmentRequestDTO
     */
    'targetUserIds'?: Array<string>;
    /**
     * An inclusive date-time when this profile is active.
     * @type {string}
     * @memberof LocalTenantProfileAssignmentRequestDTO
     */
    'validityStartTime'?: string;
    /**
     * An exclusive date-time when this profile is no longer active.
     * @type {string}
     * @memberof LocalTenantProfileAssignmentRequestDTO
     */
    'validityEndTime'?: string;
}

