/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProfileGetAPIResponseDTO } from './profile-get-apiresponse-dto';

/**
 * 
 * @export
 * @interface ProfilesGetAPIResponseDTO
 */
export interface ProfilesGetAPIResponseDTO {
    /**
     * A list of objects representing the available profiles.
     * @type {Array<ProfileGetAPIResponseDTO>}
     * @memberof ProfilesGetAPIResponseDTO
     */
    'profiles'?: Array<ProfileGetAPIResponseDTO>;
}

