/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CapabilitiesDTO } from './capabilities-dto';

/**
 * 
 * @export
 * @interface ProfileGetAPIResponseDTO
 */
export interface ProfileGetAPIResponseDTO {
    /**
     * The unique identifier associated with the profile.
     * @type {string}
     * @memberof ProfileGetAPIResponseDTO
     */
    'profileId'?: string;
    /**
     * An identifiable profile name to display in Visier. For example, \"Partner Service Manager\".
     * @type {string}
     * @memberof ProfileGetAPIResponseDTO
     */
    'displayName'?: string;
    /**
     * A list of objects representing the access that this profile has for the capabilities of this profile.
     * @type {Array<CapabilitiesDTO>}
     * @memberof ProfileGetAPIResponseDTO
     */
    'capabilities'?: Array<CapabilitiesDTO>;
    /**
     * A list of the additional capabilities that are assigned to this profile.
     * @type {Array<string>}
     * @memberof ProfileGetAPIResponseDTO
     */
    'additionalCapabilities'?: Array<string>;
}

