/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProfileAssignedForAccessibleTenantDTO
 */
export interface ProfileAssignedForAccessibleTenantDTO {
    /**
     * The unique identifier associated with the profile.
     * @type {string}
     * @memberof ProfileAssignedForAccessibleTenantDTO
     */
    'profileId'?: string;
    /**
     * An identifiable profile name to display in Visier such as \"Partner Service Manager\".
     * @type {string}
     * @memberof ProfileAssignedForAccessibleTenantDTO
     */
    'displayName'?: string;
    /**
     * The tenant code of the analytic tenant on which this profile is assigned.
     * @type {string}
     * @memberof ProfileAssignedForAccessibleTenantDTO
     */
    'tenantCode'?: string;
    /**
     * If true, the profile is assigned for all the analytic tenants of the administrating tenant.
     * @type {boolean}
     * @memberof ProfileAssignedForAccessibleTenantDTO
     */
    'forAllChildren'?: boolean;
    /**
     * An inclusive date-time when this profile is active.   Note: Long.Min_Value means that startTime is undefined.
     * @type {string}
     * @memberof ProfileAssignedForAccessibleTenantDTO
     */
    'validityStartTime'?: string;
    /**
     * An exclusive date-time when this profile is no longer active.   Note: Long.Max_Value means that endTime is undefined and is equivalent to permanent access.
     * @type {string}
     * @memberof ProfileAssignedForAccessibleTenantDTO
     */
    'validityEndTime'?: string;
}

