/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReducedErrorDTO } from './reduced-error-dto';

/**
 * 
 * @export
 * @interface ReducedUserIdErrorDTO
 */
export interface ReducedUserIdErrorDTO {
    /**
     * The bad user ID.
     * @type {string}
     * @memberof ReducedUserIdErrorDTO
     */
    'userId'?: string;
    /**
     * The details about the error.
     * @type {ReducedErrorDTO}
     * @memberof ReducedUserIdErrorDTO
     */
    'error'?: ReducedErrorDTO;
}

