/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReducedErrorDTO } from './reduced-error-dto';

/**
 * 
 * @export
 * @interface ReducedTenantCodeErrorDTO
 */
export interface ReducedTenantCodeErrorDTO {
    /**
     * The bad tenant code.
     * @type {string}
     * @memberof ReducedTenantCodeErrorDTO
     */
    'tenantCode'?: string;
    /**
     * If true, the assignment is for all the analytic tenants of the specified tenant.
     * @type {boolean}
     * @memberof ReducedTenantCodeErrorDTO
     */
    'forAllChildren'?: boolean;
    /**
     * The details about the error.
     * @type {ReducedErrorDTO}
     * @memberof ReducedTenantCodeErrorDTO
     */
    'error'?: ReducedErrorDTO;
}

