/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface SuccessfulAccessibleTenantProfileAssignmentDTO
 */
export interface SuccessfulAccessibleTenantProfileAssignmentDTO {
    /**
     * The user ID.
     * @type {string}
     * @memberof SuccessfulAccessibleTenantProfileAssignmentDTO
     */
    'userId'?: string;
    /**
     * The tenant code.
     * @type {string}
     * @memberof SuccessfulAccessibleTenantProfileAssignmentDTO
     */
    'tenantCode'?: string;
    /**
     * If true, the target assignment is for all analytic tenants.
     * @type {boolean}
     * @memberof SuccessfulAccessibleTenantProfileAssignmentDTO
     */
    'forAllChildren'?: boolean;
}

