/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TargetTenantCodeDTO
 */
export interface TargetTenantCodeDTO {
    /**
     * The tenant code.
     * @type {string}
     * @memberof TargetTenantCodeDTO
     */
    'tenantCode'?: string;
    /**
     * If true, the assignment is for all the analytic tenants of the specified tenant.
     * @type {boolean}
     * @memberof TargetTenantCodeDTO
     */
    'forAllChildren'?: boolean;
}

