/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDTO } from './error-dto';

/**
 * 
 * @export
 * @interface TenantCodeErrorDTO
 */
export interface TenantCodeErrorDTO {
    /**
     * The bad tenant code.
     * @type {string}
     * @memberof TenantCodeErrorDTO
     */
    'tenantCode'?: string;
    /**
     * If true, the target assignment is for all analytic tenants.
     * @type {boolean}
     * @memberof TenantCodeErrorDTO
     */
    'forAllChildren'?: boolean;
    /**
     * The details about the error.
     * @type {ErrorDTO}
     * @memberof TenantCodeErrorDTO
     */
    'error'?: ErrorDTO;
}

