/*
Visier Profile Management APIs

Visier APIs for managing the profiles assigned to users

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorDTO } from './error-dto';

/**
 * 
 * @export
 * @interface UserIdErrorDTO
 */
export interface UserIdErrorDTO {
    /**
     * The bad user ID.
     * @type {string}
     * @memberof UserIdErrorDTO
     */
    'userId'?: string;
    /**
     * The details about the error.
     * @type {ErrorDTO}
     * @memberof UserIdErrorDTO
     */
    'error'?: ErrorDTO;
}

